global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx-container-1'
    static_configs:
      - targets: ['192.168.146.157:9100']

  - job_name: 'nginx-container-2'
    static_configs:
      - targets: ['192.168.146.157:9101']



rule_files:
  - alert.rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 192.168.146.157:9093

