version: "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - 9090:9090
    depends_on:
      - alertmanager
 
  alertmanager:
    image: prom/alertmanager:v0.23.0
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager:/config"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug

  nginx-container-1:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - node-exporter-nginx-container-1

  nginx-container-2:
    image: nginx:latest
    ports:
      - "8081:80"
    depends_on:
      - node-exporter-nginx-container-2

  node-exporter-nginx-container-1:
    image: prom/node-exporter
    network_mode: "host"

  node-exporter-nginx-container-2:
    image: prom/node-exporter
    ports:
      - "9101:9100"
    

volumes:
  alertmanager-data:
   
     
    